### ISSUE TITLE
Invalid Python syntax

### ISSUE THREAD

**Issue by danzek** [ANSSI-FR/bits_parser#2]
The code uses invalid Python syntax and as such does not work.

```
Traceback (most recent call last):
  File "/usr/local/bin/bits_parser", line 4, in <module>
    __import__('pkg_resources').run_script('bits-parser==1.0.0', 'bits_parser')
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 1667, in run_script
    exec(code, namespace, namespace)
  File "/Library/Python/2.7/site-packages/bits_parser-1.0.0-py2.7.egg/EGG-INFO/scripts/bits_parser", line 27, in <module>
    import bits
  File "/Library/Python/2.7/site-packages/bits_parser-1.0.0-py2.7.egg/bits/__init__.py", line 8, in <module>
    from bits.bits import Bits
  File "/Library/Python/2.7/site-packages/bits_parser-1.0.0-py2.7.egg/bits/bits.py", line 175
    yield from self.parse()
             ^
SyntaxError: invalid syntax
```

**Comment by danzek** [comment]
Disregard, I see this is a new feature in Python 3.3, I was using Python 2.7.
